version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: healthcare_db
      MYSQL_ROOT_PASSWORD:
    networks:
      - health-net
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/healthcare_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=amalbasbas123456
    networks:
      - health-net

networks:
  health-net:
    driver: bridge

volumes:
  mysql_data: